version: 0.2

env:
  parameter-store:
    SONARQUBE_TOKEN: "d987597dbb86d8d1321408aae315c09a135823b0"
    SONARQUBE_ENDPOINT: "http://3.238.184.70:9000"

phases:
  install:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - sonar-scanner
